# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_dict.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, loginPage, registerPage):
        self.loginPage = loginPage
        self.registerPage = registerPage

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 677)
        MainWindow.setStyleSheet("QListWidget{\n"
"font: 20pt \"Browallia New\";\n"
"}\n"
"QTextBrowser{\n"
"font: 20pt \"Adobe 黑体 Std R\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_dict = QtWidgets.QWidget()
        self.tab_dict.setObjectName("tab_dict")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_dict)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.search_bar = QtWidgets.QLineEdit(self.tab_dict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_bar.sizePolicy().hasHeightForWidth())
        self.search_bar.setSizePolicy(sizePolicy)
        self.search_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.search = QtWidgets.QPushButton(self.tab_dict)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.splitter_2 = QtWidgets.QSplitter(self.tab_dict)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.search_result_list = QtWidgets.QListWidget(self.splitter_2)
        self.search_result_list.setMinimumSize(QtCore.QSize(100, 0))
        self.search_result_list.setObjectName("search_result_list")
        self.result_browser = QtWidgets.QTextBrowser(self.splitter_2)
        self.result_browser.setObjectName("result_browser")
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_dict, "")
        self.tab_note = QtWidgets.QWidget()
        self.tab_note.setObjectName("tab_note")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_note)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.note_title = QtWidgets.QLineEdit(self.tab_note)
        self.note_title.setMinimumSize(QtCore.QSize(0, 30))
        self.note_title.setObjectName("note_title")
        self.gridLayout_4.addWidget(self.note_title, 0, 0, 1, 1)
        self.checkBoxNote = QtWidgets.QCheckBox(self.tab_note)
        self.checkBoxNote.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/lock.jpg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/unlock.jpg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.checkBoxNote.setIcon(icon)
        self.checkBoxNote.setIconSize(QtCore.QSize(25, 25))
        self.checkBoxNote.setChecked(False)
        self.checkBoxNote.setTristate(False)
        self.checkBoxNote.setObjectName("checkBoxNote")
        self.gridLayout_4.addWidget(self.checkBoxNote, 0, 1, 1, 1)
        self.note_profile = QtWidgets.QLabel(self.tab_note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.note_profile.sizePolicy().hasHeightForWidth())
        self.note_profile.setSizePolicy(sizePolicy)
        self.note_profile.setMinimumSize(QtCore.QSize(0, 30))
        self.note_profile.setSizeIncrement(QtCore.QSize(0, 50))
        self.note_profile.setBaseSize(QtCore.QSize(0, 50))
        self.note_profile.setText("")
        self.note_profile.setObjectName("note_profile")
        self.gridLayout_4.addWidget(self.note_profile, 1, 0, 1, 1)
        self.new_button = QtWidgets.QPushButton(self.tab_note)
        self.new_button.setObjectName("new_button")
        self.gridLayout_4.addWidget(self.new_button, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.tab_note)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.note_edit = QtWidgets.QTextEdit(self.splitter)
        self.note_edit.setObjectName("note_edit")
        self.notes_list = QtWidgets.QListView(self.splitter)
        self.notes_list.setObjectName("notes_list")
        self.gridLayout_5.addWidget(self.splitter, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_note, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menulogin = QtWidgets.QMenu(self.menubar)
        self.menulogin.setObjectName("menulogin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionlogin = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/profileicon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionlogin.setIcon(icon1)
        self.actionlogin.setObjectName("actionlogin")
        self.menulogin.addAction(self.actionlogin)
        self.menubar.addAction(self.menulogin.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 自己添加的代码
        # self.notes_list.setContextMenuPolicy(3)
        # self.notes_list.customContextMenuRequested[QtCore.QPoint].connect(MainWindow.list_pop_menu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Dictionary"))
        self.search.setText(_translate("MainWindow", "搜索"))
        self.search.setShortcut(_translate("MainWindow", "Return"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dict), _translate("MainWindow", "字典"))
        self.checkBoxNote.setText(_translate("MainWindow", "编辑"))
        self.new_button.setText(_translate("MainWindow", "新建"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_note), _translate("MainWindow", "笔记"))
        self.menulogin.setTitle(_translate("MainWindow", "account"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionlogin.setText(_translate("MainWindow", "login"))
